### ISSUE TITLE
hashes are removed on pasting

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-interwikipaste#1]
When a matching URL containing a hash is pasted, the hash part seems to be lost.

Eg. `https://en.wikipedia.org/wiki/Berlin#Demographics` results in `[[wp>Berlin]]` instead `[[wp>Berlin#Demographics]]`

**Comment by annda** [comment]
Hmm, I can't reproduce the error in any way. What is your setup?

**Comment by bvdbos** [comment]
Pasting a link to `https://myownserver/doku.php/omgevingswet/bal_besluit_activiteiten_leefomgeving/gecons._tekst_bal/h3#artikel_316_aanwijzing_vergunningplichtige_gevallen` gets translated to `[[omgevingswet:bal_besluit_activiteiten_leefomgeving:gecons._tekst_bal:h3|linktext]]`

**Comment by bvdbos** [comment]
fix in https://github.com/cosmocode/dokuwiki-plugin-interwikipaste/pull/3
